### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ahcarpenter** [chef/win32-service#17]
It seems as though there is an ~5x performance decrease in terms of CPU usage when setting up a script to be run by a service via this gem as opposed to running the script manually, any ideas?

**Comment by djberg96** [comment]
@phasis68 Any thoughts?

**Comment by phasis68** [comment]
I think daemon.rb#L287 makes performance decrease
`      while(WaitForSingleObject(@@hStopEvent, 10) == WAIT_TIMEOUT)`
can be changed
`      while(WaitForSingleObject(@@hStopEvent, 1000) == WAIT_TIMEOUT)`

**Comment by djberg96** [comment]
Looks like there's been a subtle change in that value fairly recently, too. From the docs for WaitForSingleObject:

    Windows XP, Windows Server 2003, Windows Vista, Windows 7, Windows Server 2008, and 
    Windows Server 2008 R2:  The dwMilliseconds value does include time spent in low-power states.
    For example, the timeout does keep counting down while the computer is asleep.

    Windows 8, Windows Server 2012, Windows 8.1, Windows Server 2012 R2, Windows 10, and 
    Windows Server 2016 Technical Preview:  The dwMilliseconds value does not include time spent in
    low-power states. For example, the timeout does not keep counting down while the
    computer is asleep.

**Comment by djberg96** [comment]
@ahcarpenter I've updated the timeout to 1000ms for 0.8.8, which I just released, as per the suggestion from @phasis68 . Please let us know if it helps.

**Comment by djberg96** [comment]
@ahcarpenter Any improvement?

**Comment by tas50** [comment]
Closing this out due to inactivity
