### ISSUE TITLE
win32 daemon error - Service_Main thread exited abnormally

### ISSUE THREAD

**Issue by 2potatocakes** [chef/win32-service#4]
Hi Daniel,

You may already be aware of this.. But just in case.. I was playing with the Win32 daemon class and was trying to subclass off of <Daemon and was running into an error.

I had a look at your example demo_daemon.rb and I'm doing the same thing. I tried running the example and ran into the same problem. When running the equivalent of DemoDaemon.mainloop my stack trace makes it into the service_init method successfully but then errors before it gets to the service_main method throwing an error:

"Uncaught exception: Service_Main thread exited abnormally"

Anyways I'm not using it for anything, just thought I'd give you a heads up. Cheers mate

**Comment by Insood** [comment]
Had the same issue.

Turns out that the MS services had an issue with running the script over a network. ie:

\\networklocation\Redirection\insuds\Documents\Projects\LabelServer

Moving it locally fixed it for me.

**Comment by commel** [comment]
Same problem here with JRuby 1.7.22 (ignore the path, thats nasty i know) and Oracle Java 1.8.0_60 on a Windows Server 2008R2 (all 64 bit).

```ruby
F, [2015-09-08T13:21:42.017000 #2768] FATAL -- : Service_Main thread exited abnormally (RuntimeError)
C:/Program Files/xxxx/jruby-1.7.20.1/lib/ruby/gems/shared/gems/win32-service-0.8.7/lib/win32/daemon.rb:282:in `mainloop'
C:/Program Files/xxxx/jruby-1.7.20.1/lib/ruby/gems/shared/gems/win32-service-0.8.7/lib/win32/daemon.rb:217:in `mainloop'
client.rb:43:in `(root)'
```

Despite @Insnood's problem this is running locally.

**Comment by TommyLike** [comment]
`Service_Main thread exited abnormally (RuntimeError)`

Any progress??

**Comment by djberg96** [comment]
@TommyLike I'm afraid not. Help wanted.
