### ISSUE TITLE
demo_daemon.rb does not work correctly in my environment(Windows Server 2016)

### ISSUE THREAD

**Issue by hiroyuki-sato** [chef/win32-service#42]
Hello, First of all, thank you for creating the great gem.

[demo_daemon.rb](https://github.com/djberg96/win32-service/blob/ffi/examples/demo_daemon.rb) does not work correctly in my environment.
The reproduce steps and my environment is the following.
What is missing?

Best regards.

### Environment

* OS Windows Server 2016 (64bit)
* Ruby [RubyInstaller](https://rubyinstaller.org/downloads/) 2.3.3
* win32-service: 0.8.10

### Reproduce steps.

* install RubyInstaller
* Exec `gem install win32-service`
* Download 
* Execute `ruby demo_daemon.rb`

```
ruby demo_daemon.rb
```

logfile

```
more C:\Tmp\win32_daemon_test.log
0
1
2
3
4
5
6
7
8
9
Daemon failure: Service_Main thread exited abnormally
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/win32-service-0.8.10/lib/win32/daemon.rb:279:in `mainloop'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/win32-service-0.8.10/lib/win32/daemon.rb:214:in `mainloop'
demo_daemon.rb:92:in `<main>'
```

I modified `demo_daemon` for logging backtrace. 

https://github.com/djberg96/win32-service/blob/ffi/examples/demo_daemon.rb#L94

```ruby
  File.open(LOG_FILE, 'a'){ |fh| fh.puts "Daemon failure: #{err}"; fh.puts err.backtrace }
```

**Comment by djberg96** [comment]
@hiroyuki-sato I'm sorry, I do not know. Does it work if you use JRuby by any chance?

**Comment by hiroyuki-sato** [comment]
@djberg96 Thank you for the reply.

Sorry reply late.
I tried it with JRuby. I got the same error.

```
0
1
2
3
4
5
6
7
8
9
Daemon failure: Service_Main thread exited abnormally
C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/win32-service-0.8.10/lib/win32/daemon.rb:279:in `mainloop'
C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/win32-service-0.8.10/lib/win32/daemon.rb:214:in `mainloop'
demo_daemon.rb:92:in `<main>'
```

**Comment by 11v1** [comment]
> Reproduce steps.
...
    Execute ruby demo_daemon.rb

That is the problem, you should create windows service which executes demo_daemon.rb, instead of just executing demo_daemon.rb.
Command example: 
```
sc create demo_daemon binPath="C:\Ruby24-x64\bin\rubyw D:\Scripts\Redmine\demo_daemon.rb"
sc start demo_daemon
```

**Comment by hiroyuki-sato** [comment]
@11v1 Thank you for your advice. 

As you expected , I executed the following command. It seems work well. 
I'll test again later. 

```
sc create demo_daemon binPath="C:\Ruby24-x64\bin\rubyw D:\Scripts\Redmine\demo_daemon.rb"
sc start demo_daemon
```

**Comment by hiroyuki-sato** [comment]
It worked as I expected if I create windows service. Thank you.
