### ISSUE TITLE
Stub_command (mocking) Win32::Service.exists? not working 

### ISSUE THREAD

**Issue by ngeegoh** [chef/win32-service#68]
## Windows Version: Windows Server 2016 Datacenter

I have this condition in my recipe:
```ruby
install_action = (::Win32::Service.exists?(windows_service['name']) ? :configure : :create)
```
and a ChefSpec for that in spec file:
```ruby
#1: not working 
allow_any_instance_of(Win32::Service)
                .to receive(:exists?)
                .with(windows_service[:name])
                .and_return(true)
#2: also not working
stub_command("::Win32::Service.exists?(#{windows_service[:name]})").and_return(true)
```
Could you please help to find out what have I missed in the ChefSpec test that is not working and mocking the return value, or is it a bug? Thanks

**Comment by djberg96** [comment]
First one won’t work because it’s not an instance method. Not sure about the second one right off.

**Comment by ngeegoh** [comment]
Thanks for your reply @djberg96 , but the second doesn't work as well. Not sure what is the right way to mock this Win32::Service.exist? in ChefSpec test?

**Comment by djberg96** [comment]
Does this work?

`allow(Win32::Service).to receive(:exists?).with(windows_service[:name]).and_return(true)`

**Comment by ngeegoh** [comment]
It works. Thanks @djberg96
