### ISSUE TITLE
[DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS

### ISSUE THREAD

**Issue by Dreweasland** [chef/win32-service#70]
## Description
class SERVICE_STATUS_PROCESS is declared twice in structs, causing deprecation error messages with FFI

## Gem Version
2.1.4

## Windows Version
windows 10

## Replication Case
run chef-client on a windows chef node and the warning will appear
the bigger issue is that when running a bootstrap via terraform, the warning is output as an error and causing a failure

**Comment by samanthakem** [comment]
What's the ETA for this fix? I am having the same issue.

**Comment by ksandrmatveyev** [comment]
as I, with td-agent 3.6.+. Seems that 2.1.5 wasn't fix this issue https://github.com/treasure-data/omnibus-td-agent/issues/246

**Comment by tas50** [comment]
Closing this out since we removed the 2nd SERVICE_STATUS_PROCESS
