### ISSUE TITLE
win32-service gem v2.3.0 or later are not released on rubygems

### ISSUE THREAD

**Issue by cosmo0920** [chef/win32-service#79]
## Description
win32-service v2.3.0 or later gem are not released on rubygems.

## Gem Version
win32-service v.2.3.0 or later.

## Windows Version
None. This issue is no platform version related.

## Replication Case

Add the following line on Gemfile:

```gemfile
gem "win32-service", "~> 2.3.0"
```

And execute `bundle install` but no luck.

## Additional context

We use win32-service as a dependency of Fluentd to handle on Windows specific functionality.
It would be nice to release rubygems or GitHub packages as rubygems.

**Comment by tas50** [comment]
2.3.2 is up now. Internally we bump the version on each merge and promote when ready. This was intentionally not released to rubygems as it was not promoted.
